/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.nexmo.starter

import kotlin.test.Ignore
import kotlin.test.Test

class AppTest {
    @Test
    @Ignore
    fun testAppHasAGreeting() {
        // Empty Test
    }
}
